### PR TITLE
Add type parameter to GetStreamsAsync

### PR DESCRIPTION
**Pull request by pixlcrashr**
As documented in https://dev.twitch.tv/docs/api/reference#get-streams , `getStreams` allows to specify a `type` param for filtering whether or not a stream is offline or not.
This PR adds this filter to `GetStreamsAsync`.

Have a good one!

### CODE REVIEW

**Comment by Mahsaap** [comment]
It may be better to make an override for this, so we break others code that already just search for said strings in type param.
Also please target dev branch

**Comment by pixlcrashr** [comment]
> It may be better to make an override for this, so we don't break others code that already just search for said strings in type param. Also please target dev branch

We are not breaking any code since the type param has a default value null right there. This parameter provides backsupport... But if it's necessary, I can also do an override. I just do not see any reason why.

**Comment by Mahsaap** [comment]
Sry I thought you added the getstreamtype to the param in the getstreams model. Not that this was just for the call itself.

Still needs to be targeting dev branch however

**Comment by pixlcrashr** [comment]
> Still needs to be targeting dev branch however

Will do.

**Comment by Mahsaap** [comment]
Looks like I can actually redirect it, learned something new today. So I will target Dev branch and get this approved and merged.

**Comment by pixlcrashr** [comment]
> Looks like I can actually redirect it, learned something new today. So I will target Dev branch and get this approved and merged.

Sounds good to me. Thank you!

**Review by Mahsaap — APPROVED** [review]

**Review by Syzuna — APPROVED** [review]

**Pull request merged**
