### PR TITLE
Convert code to true async

### PR DESCRIPTION
**Pull request by danbopes**
Fixes some thread concurrency issues dealing with the API tokens.
ApiBase now locks securely, waits for a token per client, and fetches a new API Access token once until expired.
It's generally discouraged to Task.Run and run sync code unless it's pure CPU bound work, as you're trying up the thread pool waiting for requests to finish. Code is now completely async all the way through.

### CODE REVIEW

**Comment by danbopes** [comment]
Just realized I missed some async stuff. Going to submit another commit shortly

**Comment by Mahsaap** [comment]
pls target and reference dev for any prs

**Comment by danbopes** [comment]
@Mahsaap I don't have any clue who the devs are who manage this. Can you ping the related devs?

**Comment by LuckyNoS7evin** [comment]
> @Mahsaap I don't have any clue who the devs are who manage this. Can you ping the related devs?

@danbopes he means the dev branch not master.

Now, although I like what you have done, the API side of things is a re-write mode at the moment. We are looking to release v4 of TwitchLib later in the year. This is currently not in a visible branch as we are working on the structure of everything.

**Comment by danbopes** [comment]
@LuckyNoS7evin "Later in the year" doesn't help the current deadlock issues that are currently in this version. I can retarget the dev branch if you'd like: But these fixes offer significant improvements over current functionality, and eliminating any chance of deadlock issues from current synchronous `.GetAwaiter().GetResult()` calls.

**Comment by LuckyNoS7evin** [comment]
By all means, feel free to target dev, be aware however that whatever you do now may not, in fact will not be in the new version.

**Pull request closed without merging**
