### PR TITLE
Add two more fields...the Helix follow API returns

### PR DESCRIPTION
**Pull request by Teravus**
Adding FromName and ToName because it's free and the helix api returns them.   Why spend another API call to look these IDs up when we get both anyway...  for free.  The model only captures and exposes only the Id.
example;
{"total":2,"data":[         {"from_id":"x","from_name":"mycooltwitchNamemonkaS","to_id":"999995","to_name":"RebootTech","followed_at":"2019-04-20T00:41:59Z"},{"from_id":"myothercooltwitchNamemonkaS","from_name":"99999996","to_id":"x","to_name":"RebootTech","followed_at":"2019-04-18T00:39:55Z"}
],"pagination":{"cursor":"cursorhash_blablah"}}

### CODE REVIEW

**Comment by Teravus** [comment]
Copy that.   Will change target branch.

**Comment by Mahsaap** [comment]
Come to think of it. I cant look now but those msg Parma are going to need to be added elsewhere to get the info into the model.

**Comment by Teravus** [comment]
Cool.  I tested on my bot using the FollowerService and it populated the List<Follow> in OnNewFollowersDetectedArgs.  So...  at least that is auto-de-serializing.

**Comment by prom3theu5** [comment]
Ignore the build check on this - I've fixed the agent ^^

**Pull request merged**
