### PR TITLE
Changed API requests to use HttpClient

### PR DESCRIPTION
**Pull request by Syzuna**
Changed API requests to use HttpClient and added a custom httpmessagehandler to intercept requests and responses for logging

tests I made in my bot show that everything is working as expected!

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Looks good to me, will leave this up for a few more hours incase anyone else wants to review it. 💯

**Comment by LuckyNoS7evin** [comment]
I've had a look, seems like a good change to me..

**Comment by Syzuna** [comment]
cant test every endpoint but the stuff my bot uses works. includes besides others follower,stream,user from helix and chatters e.g.

**Comment by LuckyNoS7evin** [comment]
I'm wondering if it's worth doing DI with this and doing IHttpClient, then we can unit test the crap out of it...

**Comment by Syzuna** [comment]
IIrc there is no IHttpClient tho. an IHttpClient only exists in SignalR packages for whatever reason

**Pull request merged**
