### PR TITLE
Restructure Models.Helix / Convert LiveMonitor to Helix

### PR DESCRIPTION
**Pull request by Mahsaap**

### CODE REVIEW

**Comment by Mahsaap** [comment]
#55 #53

**Comment by Mahsaap** [comment]
hmmmm this won't have RRickkert's changes in #50 or more in the livemonitor class.

**Comment by Mahsaap** [comment]
I have updated all changes RRickkert's made and now in Helix. including all the changes in #50

**Comment by LuckyNoS7evin** [comment]
My only issue with this is the API rate limits for a clientId and having the monitor service run through helix

you get 30 calls a minute where you do not supply an access token and 120 if you supply a token. the issue with this is we would probably have to supply an access token (server generated) and pass that through. however if someone it using this and the follower service and other API calls you are going to quickly run out of room

**Comment by Mahsaap** [comment]
So that's new with helix or was that the same case with v5?

**Comment by LuckyNoS7evin** [comment]
@Mahsaap there are v5 limits but they aren't published and are ridiculously high.. the "proper" ratelimits came in with Helix

**Comment by Mahsaap** [comment]
With default checkinterval (1min) I don't think on it's own it would be much of an issue. 
Also note, followerservice is still using v5, but could probably be converted. I do believe that would use more calls then livemonitor.On another note, do you think I should use FirstOrDefault instead of First();

**Pull request merged**
