### PR TITLE
Changed .GetAwaiter().GetResult() to await

### PR DESCRIPTION
**Pull request by RRickkert**
This seems to work correctly and removes the 'dirty .GetAwaiter().GetResult()'. I think the Timer callback to an async void should be fine, but need someone to confirm this.

### CODE REVIEW

**Comment by RRickkert** [comment]
Some extra info: 

It seems to be perfectly valid to use an async void in combination with an event handler. So this should be all good!

> The guideline is to avoid async void except when used in an event handler, so using async void in an event handler is OK.

From: [https://stackoverflow.com/questions/19415646/should-i-avoid-async-void-event-handlers
](url)

**Comment by RRickkert** [comment]
Renamed some methods and variables 👍 @Syzuna

**Comment by Mahsaap** [comment]
All these changes now are in the helix conversion #56

**Comment by swiftyspiffy** [comment]
As I understand it, this PR can be closed as @Mahsaap 's PR contains these changes amongst others.

**Pull request closed without merging**
