### PR TITLE
Twitch lib/dev fix twitchid

### PR DESCRIPTION
**Pull request by Bazeloth**
Followup from https://github.com/TwitchLib/TwitchLib.Api/pull/137, now targeting dev.. ugh sorry about that

### CODE REVIEW

**Comment by Bazeloth** [comment]
I noticed the id was always `0` and since i'm using it for a sql table a unique key constraint rule was violated. Do you have an easy way to use this branch instead of the nuget package im refering to now? I'd like to use this fix asap.

**Comment by Mahsaap** [comment]
Once merged you should be able to use pre release for dev branch. But only for individual packages. Auto generated with cl builds. Keep in mind just ignore the version and use the latest dated one. Dont think that pipeline was fixed for updating version yet.

**Comment by Bazeloth** [comment]
@Mahsaap so in my case i'd have to install the `TwitchLib.Api.V5.Models` package in my projects and use prerelease when browsing nuget in order to use this fix?

**Comment by Mahsaap** [comment]
The api repo. Some use the suite. That doesnt work with prerelease.

**Comment by Bazeloth** [comment]
Alright thank you. What exactly do you mean by suite and what would it take to have this PR merged by someone?

**Comment by Bazeloth** [comment]
@swiftyspiffy My apologies if you've got a notification before, but could you have a look at this PR?

**Comment by Bazeloth** [comment]
> Alright thank you. By suite you mean https://github.com/TwitchLib/TwitchLib/blob/master/README.md?
> 
> What would it take to have this PR merged by someone? You don't have write access? I suppose @swiftyspiffy should have a look.

@Mahsaap would that be 3.0.6-C_020200107-0620234?

image

Seems kinda off to me since this PR got merged 13 hours ago. I'd assume it would've built one with todays date (which is the 15th not the 7th of january 2020)

**Comment by Bazeloth** [comment]
@Syzuna could you answer my latest question?

**Pull request merged**
