### PR TITLE
bubble the exceptions on the LiveMonitor and FollowMonitor

### PR DESCRIPTION
**Pull request by LuckyNoS7evin**
According to this article/doc

[ARTICLE/DOC](https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer?view=netcore-2.0)

All we should need is 

`Elapsed += async ( sender, e ) => await TimerElapsedAsync();`

### CODE REVIEW

**Comment by Mahsaap** [comment]
Services\Core\ServiceTimer.cs(19,53): error CS7036: There is no argument given that corresponds to the required formal parameter 'sender' of 'ServiceTimer.TimerElapsedAsync(object, ElapsedEventArgs)' [d:\a\1\s\TwitchLib.Api\TwitchLib.Api.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by LuckyNoS7evin** [comment]
Ye, just seen, I tried to change swifts branch but obviously forgot to copy paste correctly

**Comment by swiftyspiffy** [comment]
I don't think I completely understand this. Where does the consume handle these errors, and does an error effectively kill the timer? Can an elapsed event throw an exception each time without causing problems and allowing the consumer to handle the exceptions? Maybe a simple example would be good :)

**Comment by galister** [comment]
@swiftyspiffy 

> When an exception is thrown out of an async Task or async Task<T> method, that exception is captured and placed on the Task object. With async void methods, there is no Task object, so any **exceptions thrown out of an async void method will be raised directly on the SynchronizationContext** that was active when the async void method started. Figure 2 illustrates that **exceptions thrown from async void methods can’t be caught naturally.**
[ ... ]
These exceptions can be observed using AppDomain.UnhandledException or a similar catch-all event for GUI/ASP.NET applications, but using those events for regular exception handling is a recipe for unmaintainability.

source: 
https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void

**Comment by swiftyspiffy** [comment]
Fair enough. Will merge.

**Pull request merged**
