### PR TITLE
Update Soundtrack Calls / Models / XML Comments

### PR DESCRIPTION
**Pull request by Mahsaap**

### CODE REVIEW

**Comment by Mahsaap** [comment]
I'm not able to test these, if someone is able to prior to merge.

**Comment by Mahsaap** [comment]
#274

**Comment by Mahsaap** [comment]
Sounds like there is some mismatch with docs and API calls. Will likely need to revisit this as soon as the proper params are known.

**Review by Syzuna — COMMENTED** [review]
The field is still returned even tho its not updated anymore.
Should we already remove it from the model?

EDIT: I have no idea why it posted that here I was in the GetUsers PR so please ignore...

**Review by Syzuna — COMMENTED** [review]
Were the docs missmatches resolved?

**Pull request closed without merging**
