### PR TITLE
Fixed redemptionId param in GetCustomRewardRedemption

### PR DESCRIPTION
**Pull request by Yartch**
A second "reward_id" parameter was being added, instead of the expected "id".

Quick fix for issue: https://github.com/TwitchLib/TwitchLib.Api/issues/216

### CODE REVIEW

**Comment by Syzuna** [comment]
LGTM thx for caching that.

**Review by Syzuna — APPROVED** [review]

**Comment by Syzuna** [comment]
but actually one thing I just almost didnt see.. could you please rebase you PR against the dev branch?

**Comment by Yartch** [comment]
Oops sorry, is that good?

**Comment by Syzuna** [comment]
perfect 👍🏻

**Pull request merged**
