### PR TITLE
Twitch Function Released 01-15-2021 + others

### PR DESCRIPTION
**Pull request by swiftyspiffy**
This pull request has the new functionality Twitch added on January 15th 2021 + some previously missing functionality. 
This pull request is currently untested. Initial PR for feedback. Testing will be done shortly.

Support for new scopes:
 - `channel:read:editors`
 - `channel:manage:videos`
 - `user:read:blocked_users`
 - `user:manage:blocked_users`

Support for new API calls:
 - Adds `Channels` ApiBase
   - `GetChannelInformation(string broadcasterId)`
   - `ModifyChannelInformation(string broadcasterId, ModifyChannelInformationRequest request)`
   - `GetChannelEditors(string broadcasterId)`
 - Adds to `Users`:
   - `GetUserBlockList(string broadcasterId, int first = 20, string after = null)`
   - `BlockUser(string targetUserId, BlockUserSourceContextEnum? sourceContext = null, BlockUserReasonEnum? reason = null)`
   - `UnblockUser(string targetUserId)`
 - Adds to `Videos`:
   - `DeleteVideos(List<string> videoIds)`

Modify existing functionality:
 - Moved `GetVideos` models into their own package: `TwitchLib.Api.Helix.Models.Videos.GetVideos`

Internal changes:
 - Adds new ApiBase method: `TwitchPatchAsync`

### CODE REVIEW

**Review by Syzuna — CHANGES_REQUESTED** [review]
As for the sake of continuity I would like to add the Async Affix to the new Calls you added bcs they are also present for every other method

**Review by Syzuna — APPROVED** [review]

**Review by Syzuna — APPROVED** [review]

**Comment by swiftyspiffy** [comment]
Testing now.
- GetChannelInformation works

**Comment by swiftyspiffy** [comment]
- ModifyChannelInformation works
- GetChannelEditors works

**Comment by swiftyspiffy** [comment]
- GetUserBlockList works

**Comment by swiftyspiffy** [comment]
- BlockUser works
- UnblockUser works

Not able to test DeleteVideio, assuming it works.

**Pull request merged**
