### PR TITLE
fix incorrect property name in EventSubSubscription #200

### LINKED ISSUE #200: Incorrect property name for version in EventSubSubscription model
https://github.com/TwitchLib/TwitchLib.Api/blob/07beee545dcc51a2003304358a85d879a76b69f1/TwitchLib.Api.Helix.Models/EventSub/EventSubSubscription.cs#L14

The property name "id" on L14 blows up because it already exists. It should be "version".

### PR DESCRIPTION
**Pull request by keraf**
Fixes #200

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Hey! This looks good to me, but can you make the change against the `dev` branch instead of the `master` branch? We do releases from dev into master every so often, but dev is bleeding edge.

Thanks!

**Comment by keraf** [comment]
Hey! I didn't think about checking other branches first, sorry about that! I saw that `dev` already has this fix applied, I'll close this PR.

Just a quick question regarding the nuget packages. The preview ones are based off the `dev` branch, right? I'm looking to get this fix for the project I'm currently working on.

**Comment by Syzuna** [comment]
Yes previews are based on the Dev branch

**Comment by keraf** [comment]
Great, thank you!

**Pull request closed without merging**
